// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClearInputController from "./clear_input_controller"
application.register("clear-input", ClearInputController)

import DeliveryToggleController from "./delivery_toggle_controller"
application.register("delivery-toggle", DeliveryToggleController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import JointVentureController from "./joint_venture_controller"
application.register("joint-venture", JointVentureController)

import LayoutController from "./layout_controller"
application.register("layout", LayoutController)
